# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import QThread, pyqtSignal
import serial
from time import sleep

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(396, 265)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleName = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.titleName.setFont(font)
        self.titleName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titleName.setObjectName("titleName")
        self.verticalLayout.addWidget(self.titleName, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.serialText = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.serialText.setFont(font)
        self.serialText.setObjectName("serialText")
        self.horizontalLayout.addWidget(self.serialText)
        self.statusSerial = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statusSerial.setFont(font)
        self.statusSerial.setObjectName("statusSerial")
        self.horizontalLayout.addWidget(self.statusSerial)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout.addLayout(self.horizontalLayout_8)
        self.reconnectSerial = QtWidgets.QPushButton(Dialog)
        self.reconnectSerial.setObjectName("reconnectSerial")
        self.horizontalLayout.addWidget(self.reconnectSerial)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.MIDItext = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MIDItext.setFont(font)
        self.MIDItext.setObjectName("MIDItext")
        self.horizontalLayout_5.addWidget(self.MIDItext)
        self.statusMIDI = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statusMIDI.setFont(font)
        self.statusMIDI.setObjectName("statusMIDI")
        self.horizontalLayout_5.addWidget(self.statusMIDI)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_5.addLayout(self.horizontalLayout_9)
        self.reconnectMIDI = QtWidgets.QPushButton(Dialog)
        self.reconnectMIDI.setObjectName("reconnectMIDI")
        self.horizontalLayout_5.addWidget(self.reconnectMIDI)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.closeButton = QtWidgets.QPushButton(Dialog)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_7.addWidget(self.closeButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        ffe = True
        while ffe == True:
            try:
                ser = serial.Serial('COM3')
                if ser.is_open:
                    self.reconnectSerial.setEnabled(False)
                    self.statusSerial.setText('Connected')
                    ffe = False
                else:
                    self.reconnectSerial.setEnabled(True)
                    self.statusSerial.setText('Disconnected')
                    print(f"Serial port {'COM3'} is already closed")
            except serial.SerialException as e:
                    self.reconnectSerial.setEnabled(True)
                    self.statusSerial.setText('Disconnected')
                    print(f"{'COM3'}: {e}")
            
            sleep(0.01)
        
    def reconnectSerial(self):
        ser = serial.Serial('COM3',31250, timeout=1)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.titleName.setText(_translate("Dialog", "Connection Status"))
        self.serialText.setText(_translate("Dialog", "Microcontroller: "))
        self.statusSerial.setText(_translate("Dialog", " Connected"))
        self.reconnectSerial.setText(_translate("Dialog", "Reconnect"))
        self.MIDItext.setText(_translate("Dialog", "MIDI Controller: "))
        self.statusMIDI.setText(_translate("Dialog", " Connected"))
        self.reconnectMIDI.setText(_translate("Dialog", "Reconnect"))
        self.closeButton.setText(_translate("Dialog", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
